version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: on-failure:5
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    name: mysql
