services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432