services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: postgres
    restart: on-failure:5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
    name: postgres